sudo: false
language: node_js
node_js:
- '5.9'
cache:
  directories:
  - node_modules
env:
  global:
    secure: nVVJ+0/ZnZ6UusDLebf4Nd8eIP5Omj4ogJ+x/lzBOgzy8jZRV7KktEEjnrefFbzV5ICZomVdgNXuJyGJyQsjy2R3nMP5TnJ+abd6Fcpi6dp4MIQc7KmnRKLo1qg/Tdue3T93bXSNZht73Fm6M/jSkFswsBQHS+OfCnZbSEkEc7CmESTJRHeGleUAzRJho0Di/FPm4JV4w1tQJLVw/lSd1PR9ucHEwxaUiMRgWO1ttOg7rv7c55tc9zx4FMgvyUe1v0oSNRN8TTJYLNO2I6SOMcuyLYkwgHNjMvuHl0vO6BeCRq1Ys8S3zvKFtk9nQnceHc6sMSI5aQCJrqji5MQLiy48KVbOEfmm+jJ6KkM3ZUGg0cS+ijRcCHWEDzOs9TXlaDyvEuhR7RcHvRXsO5ZI0ijFATla7cWKqzKwhPCFoZimi2mOHRp+d3WOHqt0k2DBKFHE9ZBwKKEgQf4vh3XQPsL3UCvdBpunwmdFMnrxLPhLqSxGhP604hvUC4heFbY9KKKpncoQmYu5rll0nk1ADU6hIYmjFUQm3czn+NiC2rnpf9yACSw+OybzBK00Bn8Hu58unIkbJp1sf9KOyN+14pJkg3FPvuhdfAfeoNJuyTB5c4yTbs1Z6L+5ccTUrUJc1cMmgk/h1YQLwJLHjH3ykCDFtEYA1x3cIt8rzQpbcgA=
notifications:
  slack:
    secure: fxlZF300yGU8tH0lO+VWS9Ox6L85saOXI/k1tc9ZDDjVDvTzGKHRnIazVHVA6k3VPDdDQ8gbaNLfOMe2etaWyEWd5zXkcpc4FQ3sO20iVN3utYPOkr5Ufv3+yxpF3EIcEEomKtrlHKnWs3OElulVlF4tNzHZFoeybxX7GINGOnUYfVOk4IFx6+BRpHy898EtKpPsoR6VnCZR/+i/B7J+FR1LZm1CYQQcy/3HBZsQFvl91A13iD+AtQYuVbgnWHheUQO3doBrE6bJz8EvwZ90rjVke/bHZFJfCXitH2qWGWMUIKTm85Fi2FDFeHGBXklLrPuADCcqMJrndHNgJi/vYxDCpA3Lo7kpV0fd3/eU830U0tAomdpjSFijWEjUvtHprqu4O3irkC4isFIf/ceZ8y0kcZzOQphV1IakG2dBlEjNMMulAydIjSSKohI5QF2/wnKS+qY7i4uvFKibVlXDJDEwFK4PaGXKfXRCaXwSmNttt7SRFe2uuqpb9qAu2e5MqhXIbx0IMlVaNuwJO5J9naF/0EecB6P+cPQD2fBoK8pRu1MLxNsjsdtX3ntM7Q1FKW76nbhNReRkqeunwxKMZs+hVmMlP0smhTlPIy7juflqvxV4ed8/nqzv+fMdpBD3UppkKAGz5pFaXSRzcoMonm9nskNf9FRSVlMc98LHtx0=
